''' Notes '''
NOTE_A = "A"
NOTE_B = "B"
NOTE_C = "C"
NOTE_D = "D"
NOTE_E = "E"
NOTE_F = "F"
NOTE_G = "G"

NOTES = [
	NOTE_A, NOTE_B, NOTE_C, NOTE_D,
	NOTE_E, NOTE_F, NOTE_G
]

''' Accidentals '''
TONE_FLAT = "b"
TONE_SHARP = "#"
TONE_NATURAL = ""

''' Intervals '''
INTVL_MIN_2 = 1
INTVL_MAJ_2 = 2
INTVL_MIN_3 = 3
INTVL_MAJ_3 = 4
INTVL_PER_4 = 5
INTVL_AUG_4 = 6
INTVL_DIM_5 = 6
INTVL_PER_5 = 7
INTVL_AUG_5 = 8
INTVL_MIN_6 = 8
INTVL_MAJ_6 = 9
INTVL_MIN_7 = 10
INTVL_MAJ_7 = 11

''' Menu options '''
OPTN_EXIT = 0
OPTN_CHOOSE_ROOT = 1
OPTN_CALC_INTVL = 2
OPTN_GET_NOTES = 3
OPTN_GET_CHORDS = 4