''' Notes '''
NOTE_A = "A"
NOTE_B = "B"
NOTE_C = "C"
NOTE_D = "D"
NOTE_E = "E"
NOTE_F = "F"
NOTE_G = "G"

NOTES = [
	NOTE_A, NOTE_B, NOTE_C, NOTE_D,
	NOTE_E, NOTE_F, NOTE_G
]

''' Accidentals '''
TONE_FLAT = "b"
TONE_SHARP = "#"
TONE_NATURAL = ""

''' Tonalities '''
TONALITY_MAJOR = 0
TONALITY_MINOR = 1

''' Intervals '''
INTVL_ROOT	= 0
INTVL_MIN_2 = 1
INTVL_MAJ_2 = 2
INTVL_MIN_3 = 3
INTVL_MAJ_3 = 4
INTVL_PER_4 = 5
INTVL_AUG_4 = 6
INTVL_DIM_5 = 6
INTVL_PER_5 = 7
INTVL_AUG_5 = 8
INTVL_MIN_6 = 8
INTVL_MAJ_6 = 9
INTVL_MIN_7 = 10
INTVL_MAJ_7 = 11
INTVL_MAJ_9	= 14
INTVL_AUG_9	= 15
INTVL_MAJ_11 = 17
INTVL_AUG_11 = 18
INTVL_MAJ_13 = 21

INTVL_DICT = {
	INTVL_ROOT	: "R",
	INTVL_MIN_2 : "b2",
	INTVL_MAJ_2 : "2",
	INTVL_MIN_3 : "b3",
	INTVL_MAJ_3 : "3",
	INTVL_PER_4 : "4",
	INTVL_AUG_4 : "#4",
	INTVL_DIM_5 : "b5",
	INTVL_PER_5 : "5",
	INTVL_AUG_5 : "#5",
	INTVL_MIN_6 : "b6",
	INTVL_MAJ_6 : "6",
	INTVL_MIN_7 : "b7",
	INTVL_MAJ_7 : "7",
	INTVL_MAJ_9	: "9",
	INTVL_AUG_9	: "#9",
	INTVL_MAJ_11 : "11",
	INTVL_AUG_11 : "#11",
	INTVL_MAJ_13 : "13"
}

''' Chords '''
# simple chords
CHORD_MAJ 	= [ INTVL_MAJ_3, INTVL_PER_5 ]
CHORD_MIN 	= [ INTVL_MIN_3, INTVL_PER_5 ]
CHORD_SUS_4 = [ INTVL_PER_4, INTVL_PER_5 ]
CHORD_SUS_2	= [ INTVL_MAJ_2, INTVL_PER_5 ]
CHORD_AUG	= [ INTVL_MAJ_3, INTVL_AUG_5 ]
CHORD_5 	= [ INTVL_PER_5 ]
CHORD_DIM	= [ INTVL_MIN_3, INTVL_DIM_5 ]
# 7 chords
CHORD_DOM_7	= CHORD_MAJ + [ INTVL_MIN_7 ]
CHORD_MAJ_7 = CHORD_MAJ + [ INTVL_MAJ_7 ] 
CHORD_MIN_7 = CHORD_MIN + [ INTVL_MIN_7 ]
CHORD_MAJ_6	= CHORD_MAJ + [ INTVL_MAJ_6 ]
CHORD_MIN_6 = CHORD_MIN + [ INTVL_MAJ_6 ]
CHORD_DIM_7	= CHORD_DIM + [ INTVL_MAJ_6 ]
CHORD_HALF_DIM_7 = CHORD_DIM + [ INTVL_MIN_7 ]
CHORD_7_SHRP_5	= CHORD_AUG + [ INTVL_MIN_7 ]
# 9 chords
CHORD_9	= CHORD_DOM_7 + [ INTVL_MAJ_9 ]
CHORD_7_SHRP_9	= CHORD_DOM_7 + [ INTVL_AUG_9 ]
CHORD_MAJ_9	= CHORD_MAJ_7 + [ INTVL_MAJ_9 ]
CHORD_ADDED_9 = CHORD_MAJ + [ INTVL_MAJ_9 ]
CHORD_MIN_9 = CHORD_MIN_7 + [ INTVL_MAJ_9 ]
CHORD_MIN_ADD_9 = CHORD_MIN + [ INTVL_MAJ_9 ]
# 11/13 chords
CHORD_11 = [ INTVL_PER_5, INTVL_MIN_7, INTVL_MAJ_9, INTVL_MAJ_11 ]
CHORD_MIN_11 = CHORD_MIN_9 + [ INTVL_MAJ_11 ]
CHORD_DOM_7_SHRP_11 = CHORD_DOM_7 + [ INTVL_AUG_11 ]
CHORD_MAJ_7_SHRP_11 = CHORD_MAJ_9 + [ INTVL_AUG_11 ]
CHORD_13 = CHORD_9 + [ INTVL_MAJ_13 ]
CHORD_MAJ_13 = CHORD_MAJ_9 + [ INTVL_MAJ_13 ]
CHORD_MIN_13 = CHORD_MIN_11 + [ INTVL_MAJ_13 ]

''' Menu options '''
OPTN_EXIT = 0
OPTN_CHOOSE_ROOT = 1
OPTN_SHOW_ROOTS = 2 
OPTN_CALC_INTVL = 3
OPTN_GET_NOTES = 4
OPTN_GET_CHORDS = 5