''' Notes '''
NOTE_A = "A"
NOTE_B = "B"
NOTE_C = "C"
NOTE_D = "D"
NOTE_E = "E"
NOTE_F = "F"
NOTE_G = "G"

NOTES = [
	NOTE_A, NOTE_B, NOTE_C, NOTE_D,
	NOTE_E, NOTE_F, NOTE_G
]

''' Accidentals '''
TONE_FLAT = "b"
TONE_DOUBLE_FLAT = "bb"
TONE_SHARP = "#"
TONE_DOUBLE_SHARP = "##"
TONE_NATURAL = ""

''' Tonalities '''
TONALITY_MAJOR = "major"
TONALITY_MINOR = "minor"

''' Intervals '''
INTVL_ROOT	= 0
INTVL_MIN_2 = 1
INTVL_MAJ_2 = 2
INTVL_MIN_3 = 3
INTVL_MAJ_3 = 4
INTVL_PER_4 = 5
INTVL_AUG_4 = 6
INTVL_DIM_5 = 6
INTVL_PER_5 = 7
INTVL_AUG_5 = 8
INTVL_MIN_6 = 8
INTVL_MAJ_6 = 9
INTVL_MIN_7 = 10
INTVL_MAJ_7 = 11
INTVL_OCTAVE = 12
INTVL_MAJ_9	= 14
INTVL_AUG_9	= 15
INTVL_MAJ_11 = 17
INTVL_AUG_11 = 18
INTVL_MAJ_13 = 21

INTVL_DICT = {
	INTVL_ROOT	: "R",
	INTVL_MIN_2 : "b2",
	INTVL_MAJ_2 : "2",
	INTVL_MIN_3 : "b3",
	INTVL_MAJ_3 : "3",
	INTVL_PER_4 : "4",
	INTVL_AUG_4 : "#4",
	INTVL_DIM_5 : "b5",
	INTVL_PER_5 : "5",
	INTVL_AUG_5 : "#5",
	INTVL_MIN_6 : "b6",
	INTVL_MAJ_6 : "6",
	INTVL_MIN_7 : "b7",
	INTVL_MAJ_7 : "7",
	INTVL_MAJ_9	: "9",
	INTVL_AUG_9	: "#9",
	INTVL_MAJ_11 : "11",
	INTVL_AUG_11 : "#11",
	INTVL_MAJ_13 : "13"
}

''' Chords '''
# simple chords
CHORD_MAJ 		= ""
CHORD_MIN 		= "m"
CHORD_SUS_4 	= "sus4"
CHORD_SUS_2		= "sus2"
CHORD_AUG		= "aug"
CHORD_5 		= "5"
CHORD_DIM		= "dim"
# 7 chords
CHORD_DOM_7		= "7"
CHORD_MAJ_7 	= "M7"
CHORD_MIN_7 	= "m7"
CHORD_MAJ_6		= "M6"
CHORD_MIN_6 	= "m6"
CHORD_DIM_7		= "dim7"
CHORD_HALF_DIM_7 	= "m7b5"
CHORD_7_SHRP_5		= "7#5"
# 9 chords
CHORD_9			= "9"
CHORD_7_SHRP_9	= "7#9"
CHORD_MAJ_9		= "M9"
CHORD_ADDED_9 	= "add9"
CHORD_MIN_9 	= "m9"
CHORD_MIN_ADD_9 = "m add9"
# 11/13 chords
CHORD_11 		= "11"
CHORD_MIN_11 	= "m11"
CHORD_DOM_7_SHRP_11 = "dom7#11"
CHORD_MAJ_7_SHRP_11 = "M7#11"
CHORD_13 		= "13"
CHORD_MAJ_13 	= "M13"
CHORD_MIN_13 	= "m13"

CHORD_INTVL_DICT = {
	CHORD_MAJ 	: [ INTVL_MAJ_3, INTVL_PER_5 ],
	CHORD_MIN 	: [ INTVL_MIN_3, INTVL_PER_5 ],
	CHORD_SUS_4 : [ INTVL_PER_4, INTVL_PER_5 ],
	CHORD_SUS_2	: [ INTVL_MAJ_2, INTVL_PER_5 ],
	CHORD_AUG	: [ INTVL_MAJ_3, INTVL_AUG_5 ],
	CHORD_5 	: [ INTVL_PER_5 ],
	CHORD_DIM	: [ INTVL_MIN_3, INTVL_DIM_5 ],
	CHORD_DOM_7	: [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MIN_7 ],
	CHORD_MAJ_7 : [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MAJ_7 ],
	CHORD_MIN_7 : [ INTVL_MIN_3, INTVL_PER_5, INTVL_MIN_7 ],
	CHORD_MAJ_6	: [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MAJ_6 ],
	CHORD_MIN_6 : [ INTVL_MIN_3, INTVL_PER_5, INTVL_MAJ_6 ],
	CHORD_DIM_7	: [ INTVL_MIN_3, INTVL_DIM_5, INTVL_MAJ_6 ],
	CHORD_HALF_DIM_7 : [ INTVL_MIN_3, INTVL_DIM_5, INTVL_MIN_7 ],
	CHORD_7_SHRP_5	: [ INTVL_MAJ_3, INTVL_AUG_5, INTVL_MIN_7 ],
	CHORD_9	: [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MIN_7, INTVL_MAJ_9 ],
	CHORD_7_SHRP_9	: [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MIN_7, INTVL_AUG_9 ],
	CHORD_MAJ_9	: [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MAJ_7, INTVL_MAJ_9 ],
	CHORD_ADDED_9 : [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MAJ_9 ],
	CHORD_MIN_9 : [ INTVL_MIN_3, INTVL_PER_5, INTVL_MIN_7, INTVL_MAJ_9 ],
	CHORD_MIN_ADD_9 : [ INTVL_MIN_3, INTVL_PER_5, INTVL_MAJ_9 ],
	CHORD_11 : [ INTVL_PER_5, INTVL_MIN_7, INTVL_MAJ_9, INTVL_MAJ_11 ],
	CHORD_MIN_11 : [ INTVL_MIN_3, INTVL_PER_5, INTVL_MIN_7, INTVL_MAJ_9, INTVL_MAJ_11 ],
	CHORD_DOM_7_SHRP_11 : [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MIN_7, INTVL_AUG_11 ],
	CHORD_MAJ_7_SHRP_11 : [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MAJ_7, INTVL_MAJ_9, INTVL_AUG_11 ],
	CHORD_13 : [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MIN_7, INTVL_MAJ_9, INTVL_MAJ_13 ],
	CHORD_MAJ_13 : [ INTVL_MAJ_3, INTVL_PER_5, INTVL_MAJ_7, INTVL_MAJ_9, INTVL_MAJ_13 ],
	CHORD_MIN_13 : [ INTVL_MIN_3, INTVL_PER_5, INTVL_MIN_7, INTVL_MAJ_9, INTVL_MAJ_11, INTVL_MAJ_13 ]
}


''' Menu options '''
OPTN_EXIT 				= 0
OPTN_CHOOSE_KEY 		= 1
OPTN_GET_NOTES_IN_KEY 	= 2
OPTN_GET_CHORDS_IN_KEY 	= 3
OPTN_GET_INTERVALS		= 4
OPTN_VIEW_INSTRUMENT	= 5

MAIN_MENU_DICT = {
	OPTN_CHOOSE_KEY : "Set key",
	OPTN_GET_NOTES_IN_KEY : "Get notes in key",
	OPTN_GET_CHORDS_IN_KEY : "Get chords in key",
	OPTN_GET_INTERVALS : "Get intervals of root",
	OPTN_VIEW_INSTRUMENT : "Instrument viewer",
	OPTN_EXIT : "Exit"
}

OPTN_BACK				= 0
OPTN_DISPLAY_ROOTS		= 1
OPTN_DISPLAY_NOTES_IN_KEY = 2
OPTN_DISPLAY_CHORD		= 3
OPTN_DISPLAY_SCALE		= 4

INSTRUMENT_MENU_DICT = {
	OPTN_DISPLAY_ROOTS : "Display root positions",
	OPTN_DISPLAY_NOTES_IN_KEY : "Display notes in key on instrument",
	OPTN_DISPLAY_CHORD : "Display chord on instrument",
	OPTN_DISPLAY_SCALE : "Display scale on instrument",
	OPTN_BACK : "Back"
}
